In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread("/media/yashjonjale/Elements/My_workspace/SOC_lane_detection/input_images/in_img1.jpg")
print(img)
cv2.imshow("img1",img)


[[[179 179 179]
  [178 178 178]
  [178 178 178]
  ...
  [178 178 178]
  [178 178 178]
  [178 178 178]]

 [[179 179 179]
  [178 178 178]
  [178 178 178]
  ...
  [178 178 178]
  [178 178 178]
  [178 178 178]]

 [[179 179 179]
  [178 178 178]
  [178 178 178]
  ...
  [178 178 178]
  [178 178 178]
  [178 178 178]]

 ...

 [[151 151 151]
  [135 135 135]
  [168 168 168]
  ...
  [147 147 147]
  [167 167 167]
  [151 151 151]]

 [[128 128 128]
  [119 119 119]
  [134 134 134]
  ...
  [184 184 184]
  [148 148 148]
  [125 125 125]]

 [[131 131 131]
  [105 105 105]
  [140 140 140]
  ...
  [204 204 204]
  [176 176 176]
  [123 123 123]]]


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/yashjonjale/.local/lib/python3.10/site-packages/cv2/qt/plugins"
